-- Insérer les 3 comptes utilisateur avec leurs profils
-- Note: Les mots de passe seront cryptés par Supabase lors de la création

-- Insérer les utilisateurs dans auth.users (via les fonctions Supabase)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_sent_at,
  recovery_token,
  email_change_sent_at,
  email_change,
  email_change_token_new,
  email_change_token_current,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at
) VALUES 
(
  '00000000-0000-0000-0000-000000000000',
  'caissier-uuid-0001',
  'authenticated',
  'authenticated',
  'caisse@dolceitalia.fr',
  crypt('Dolce961', gen_salt('bf')),
  now(),
  now(),
  '',
  null,
  '',
  null,
  '',
  '',
  '',
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"nom": "Caissier", "role": "caissier"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  0,
  null,
  '',
  null
),
(
  '00000000-0000-0000-0000-000000000000',
  'pizzaiolo-uuid-0002',
  'authenticated',
  'authenticated',
  'cuisine@dolceitalia.fr',
  crypt('Dolce961', gen_salt('bf')),
  now(),
  now(),
  '',
  null,
  '',
  null,
  '',
  '',
  '',
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"nom": "Pizzaiolo", "role": "pizzaiolo"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  0,
  null,
  '',
  null
),
(
  '00000000-0000-0000-0000-000000000000',
  'livreur-uuid-0003',
  'authenticated',
  'authenticated',
  'livraison@dolceitalia.fr',
  crypt('Dolce961', gen_salt('bf')),
  now(),
  now(),
  '',
  null,
  '',
  null,
  '',
  '',
  '',
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"nom": "Livreur", "role": "livreur"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  0,
  null,
  '',
  null
);

-- Insérer les profils correspondants
INSERT INTO public.profiles (user_id, nom, role) VALUES
('caissier-uuid-0001', 'Caissier', 'caissier'),
('pizzaiolo-uuid-0002', 'Pizzaiolo', 'pizzaiolo'),
('livreur-uuid-0003', 'Livreur', 'livreur');