// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rllqnpopmacbyyhnhljc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsbHFucG9wbWFjYnl5aG5obGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjA2NjQsImV4cCI6MjA3MzUzNjY2NH0.FX2YUqRe9iYwrlYhhfsWOvcYq9YhrCgc7wRGlryB5jM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});